# Server key for viewer connections
key = "test"

# Port to websockets/js server
port = 3333

# Full hostname and port (if needed) WITHOUT PROTOCOL
hostname = "localhost:3333"

# Update interval to check server status (in seconds)
update_interval = 1

# If a viewer request server info, should it be requested to
# the server or should we send the info we have stored?
cache_updates = true
